TODO items annotated with issue numbers
LNP-BP/rust-lnpbp pull request #197
Opened 2021-03-22 17:20 UTC by rajarshimaitra

2021-03-30 08:36 UTC, dr-orlovsky requested changes
Everythin is ok apart from `(new)` prefixes which I removed with suggestions

2021-03-30 08:36 UTC, dr-orlovsky commented on src/chain.rs
> +// TODO #186: (new) Move constants to rust-bitcoin
```suggestion
// TODO #186: Move constants to rust-bitcoin
```

2021-03-30 08:36 UTC, dr-orlovsky commented on src/chain.rs
> +        // TODO #187: (new) update with first RGB release
```suggestion
        // TODO #187: update with first RGB release
```

2021-03-30 08:36 UTC, dr-orlovsky commented on src/chain.rs
> +        // TODO #187: (new) update with first RGB release
```suggestion
        // TODO #187: update with first RGB release
```

2021-03-30 08:36 UTC, dr-orlovsky commented on src/chain.rs
> +        // TODO #188: (new) check Liquid network magic number and change this if needed
```suggestion
        // TODO #188: check Liquid network magic number and change this if needed
```

2021-03-30 08:36 UTC, dr-orlovsky commented on src/tweak.rs
> +    // TODO #190: (new) Once miniscript will do a better descriptor parse errors,
```suggestion
    // TODO #190: Once miniscript will do a better descriptor parse errors,
```

2021-03-30 08:36 UTC, dr-orlovsky commented on strict_encoding/src/test_helpers.rs
> +// TODO #196: (new) Move into derive macro
```suggestion
// TODO #196: Move into derive macro
```

2021-03-30 14:18 UTC, rajarshimaitra commented
Updated..

2021-04-11 13:51 UTC, dr-orlovsky approved these changes

2021-04-11 13:51 UTC, merged